print("Please enter the class name")
classname = input()
print("Please enter the first pupil's name")
pupil1_name = input()
print("Please enter the second pupil's name")
pupil2_name = input()
print("Please enter the third pupil's name")
pupil3_name = input()
print("Please enter the forth pupil's name")
pupil4_name = input()
print("Please enter the fifth pupil's name")
pupil5_name = input()
print("Please enter the sixth pupil's name")
pupil6_name = input()
print("Please enter the seventh pupil's name")
pupil7_name = input()
print("Please enter the eighth pupil's name")
pupil8_name = input()
print("Please enter the ninth pupil's name")
pupil9_name = input()
print("Please enter the tenth pupil's name")
pupil10_name = input()
print("Please enter the first pupil's percentage score")
pupil1_percentagescore = int(input())
print("Please enter the second pupil's percentage score")
pupil2_percentagescore = int(input())
print("Please enter the third pupil's percentage score")
pupil3_percentagescore = int(input())
print("Please enter the forth pupil's percentage score")
pupil4_percentagescore = int(input())
print("Please enter the fifth pupil's percentage score")
pupil5_percentagescore = int(input())
print("Please enter the sixth pupil's percentage score")
pupil6_percentagescore = int(input())
print("Please enter the seventh pupil's percentage score")
pupil7_percentagescore = int(input())
print("Please enter the eighth pupil's percentage score")
pupil8_percentagescore = int(input())
print("Please enter the ninth pupil's percentage score")
pupil9_percentagescore = int(input())
print("Please enter the tenth pupil's percentage score")
pupil10_percentagescore = int(input())
classname_score_raw = int((pupil1_percentagescore + pupil2_percentagescore + pupil3_percentagescore + pupil4_percentagescore + pupil5_percentagescore + pupil6_percentagescore + pupil7_percentagescore + pupil8_percentagescore + pupil9_percentagescore + pupil10_percentagescore))
classname_score = str(classname_score_raw // 10)
print("The class average score was" + " " + classname_score)
for 
test = input()
